### ISSUE TITLE
Changes to 'vars' file?

### ISSUE THREAD

**Issue by roytruelove** [ogarcia/docker-taskd#1]
Hi @ogarcia, I was wondering why your build doesn't make any changes to the `vars` file for cert generation.  The [docs](https://taskwarrior.org/docs/taskserver/configure.html) mention that it _must_ be changed; are you still able to run the server w/out this?

**Comment by ogarcia** [comment]
Hi! @roytruelove,

The main idea is that the init script build a sample configuration if `${TASKDATA}/config` not exists (as you can see in [run.sh][1]). But if you make your own configuration file with your certificates the `run.sh` only starts the app.

Remember that you must store your data and certificates in a non-volatile volume.

If you wish use the tools inside the docker, you always do:
``` bash
# To start container
docker run -d --name=taskd -p 53589:53589 \
 -v /where/you/stor/your/data:/var/taskd \
 ogarcia/taskd
# To get a shell
docker exec -t -i taskd /bin/sh
```

And rebuild the certificates as you wish :wink: 

[1]: https://github.com/ogarcia/docker-taskd/blob/master/docker/run.sh#L10

**Comment by roytruelove** [comment]
Thank you sir 👍
