### ISSUE TITLE
use let’s encrypt certificate with container

### ISSUE THREAD

**Issue by Phylex** [ogarcia/docker-taskd#11]
Hey, this container looks really neat to set up taskd with the setup I am using.
I am using traefik for routing various things to different containers and have my own domain. It also regenerates the TLS certificates every few months. The Variables that are passed as well as the Documentation of the taskd say that I need to generate a frew things. I think I know how to the TLS certificates work, but seemingly taskd does something with a client certificate that I don’t quite understand. Would it be possible to help me integrate a procedure into the container, where it is possible to use the lets encrypt certificats.
Sorry for the not to technical comment, (I’m more the programmer, less the devops engineer)
Thanks so much already.

**Comment by ogarcia** [comment]
That is out of the context of this repository. If you want to configure on your own the certificate with Let's Encrypt (or any other certificate authority) you can do it by simply mounting your own `/var/taskd` data volume with those certificates, but as I said, that's up to you how you want to deploy the solution.

You don't need to use Let's Encrypt certificates for this anyway, the system will work exactly the same simply using the certificates it generates.

**Comment by traycerb** [comment]
Not the OP, so apologies for bringing this back up again, but would you mind using pre-existing certficates to see if they work?  

I spun up a brand new container using the relevant environment variables, copied the brand-new certificates to my client and was able to access everything remotely and it worked perfectly.

I made them permanent so I wouldn't have to copy the certificates to the client again, as you advised by:

> mounting your own `/var/taskd` data volume with existing certificates.

This worked great, and even remotely too, but I needed to update and restart my server (Synology NAS running it's own flavor of Linux), and upon restarting the Docker `taskd `server , nothing works.  There are no errors, the `taskd `server starts and exits within a few seconds.

`docker run -d   --name=taskd   -p 53589:53589   -v /srv/taskd:/var/taskd   connectical/taskd`

running `docker ps -a` shows `taskd ` exits after starts (this was screenshotted later, which is why it says `57 minutes`)

```
root@XXXXXXXXXX:/srv/taskd/pki# docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                      PORTS                      NAMES
6c8905c369d7   connectical/taskd                "/app/taskd/run.sh"      57 minutes ago   Exited (0) 57 minutes ago                              taskd

```
I thought it might be a permissions thing so I opened a session using interactive mode:

`  sudo docker run -ti -p 53589:53589 -v /srv/taskd:/var/taskd connectical/taskd /bin/sh`

Running the diagnostics, I don't see any issue:


```
/var/taskd/pki # taskd diagnostics --data /var/taskd

taskd 1.1.0
    Platform: Linux
    Hostname: 1583bff7e60b

Compiler
     Version: 12.2.1 20220924
        Caps: +stdc +stdc_hosted +200809 +LP64 +c8 +i32 +l64 +vp64 +time_t64
  Compliance: C++11

Build Features
       Built: Oct 14 2022 15:22:08
       CMake: 3.24.2
     libuuid: libuuid + uuid_unparse_lower
   libgnutls: 3.7.8
  Build type: None

Configuration
   TASKDDATA: /var/taskd
        root: /var/taskd (readable)
      config: /var/taskd/config (readable)
          CA: /var/taskd/pki/ca.cert.pem (readable)
 Certificate: /var/taskd/pki/server.cert.pem (readable)
         Key: /var/taskd/pki/server.key.pem (readable)
         CRL: /var/taskd/pki/server.crl.pem (readable)
         Log: /var/taskd/log/taskd.log (found)
    PID File: /var/taskd/taskd.pid (found)
      Server: XXXXXXXXXXXXX:53589
 Max Request: 1048576 bytes
     Ciphers:
       Trust: strict
```

I tried launching the server directly from within docker using verbose logging and this is what I see:
```
/var/taskd/pki # taskd server --debug --debug.tls=3
s: INFO Client certificate will be verified.
s: 3 ASSERT: x509_ext.c[gnutls_subject_alt_names_get]:111
s: 3 ASSERT: x509.c[get_alt_name]:2012
s: 3 ASSERT: mpi.c[wrap_nettle_mpi_print]:60
s: 2 added 6 protocols, 29 ciphersuites, 19 sig algos and 10 groups into priority list
/var/taskd/pki # ps -leaf
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/sh
   71 root      0:00 ps -leaf
/var/taskd/pki #

```

The log provides no extra information:
```
2023-05-13 22:43:52 ==== taskd 1.1.0  ====
2023-05-13 22:43:52 Serving from /var/taskd
2023-05-13 22:43:52 Debug mode
2023-05-13 22:43:52 Using address XXXXXXXXXXXX
2023-05-13 22:43:52 Using port 53589
2023-05-13 22:43:52 Using family
2023-05-13 22:43:52 Queue size 10 requests
2023-05-13 22:43:52 Request size limit 1048576 bytes
2023-05-13 22:43:52 IP logging on
2023-05-13 22:43:52 CA          /var/taskd/pki/ca.cert.pem
2023-05-13 22:43:52 Certificate /var/taskd/pki/server.cert.pem
2023-05-13 22:43:52 Private Key /var/taskd/pki/server.key.pem
2023-05-13 22:43:52 CRL         /var/taskd/pki/server.crl.pem
2023-05-13 22:43:52 Server starting
2023-05-13 22:43:57 Try again

```

My config is pretty straightforward:
```
confirmation=1
extensions=/usr/libexec/taskd
ip.log=on
log=/var/taskd/log/taskd.log
pid.file=/var/taskd/taskd.pid
queue.size=10
request.limit=1048576
root=/var/taskd
server=XXXXXXXXXXXXXXX:53589
trust=strict
verbose=1
client.cert=/var/taskd/pki/client.cert.pem
client.key=/var/taskd/pki/client.key.pem
server.cert=/var/taskd/pki/server.cert.pem
server.key=/var/taskd/pki/server.key.pem
server.crl=/var/taskd/pki/server.crl.pem
ca.cert=/var/taskd/pki/ca.cert.pem
debug.tls=3
```

Any ideas? Can you replicate this?  I know if I remove the existing certificates, and they are generated again, it will work fine, but copying the certificates each time isn't practical.  I'm not sure if it's a `taskd `thing or a `Docker `thing, but I'm at the limits of my ability to understand it 😢

**Comment by ogarcia** [comment]
@traycerb I can't think what might be going on. If it works locally but not on the NAS, maybe it's something that the NAS is doing with its modified Linux, but I can't tell you anything more about it.

I don't know if opening a ticket to the taskd developer can tell you how to do a more exhaustive debug.

**Comment by traycerb** [comment]
thanks for taking the time to reply. 

it does work on the NAS, it just doesn't work when I use pre-existing certificates, as opposed to the ones created by the container the very first time. 

I will check with the `taskd` developers.

**Comment by ogarcia** [comment]
> it does work on the NAS, it just doesn't work when I use pre-existing certificates, as opposed to the ones created by the container the very first time.

This may be due to certificate extensions. My advice is to generate the certificates with the container itself by [changing the environment variables](https://github.com/ogarcia/docker-taskd#environment-variables) to suit what you want.

**Comment by traycerb** [comment]
> > it does work on the NAS, it just doesn't work when I use pre-existing certificates, as opposed to the ones created by the container the very first time.
> 
> This may be due to certificate extensions. My advice is to generate the certificates with the container itself by [changing the environment variables](https://github.com/ogarcia/docker-taskd#environment-variables) to suit what you want.

well, in fact the certificates I used **were** the ones generated by altering those environment variables.  Everything works the first time when the certificates are first created, but when I eventually I need to restart the container and try to re-use the certificates (having copied them to a docker volume), that's when it fails.

I appreciate your responses, and it's not fair for me to take up more of your time, but before I leave you alone, can I ask if you've been able to re-use certificates using a permanent volume?

**Comment by ogarcia** [comment]
> I appreciate your responses, and it's not fair for me to take up more of your time, but before I leave you alone, can I ask if you've been able to re-use certificates using a permanent volume?

Yes of course, in fact you can see in the README that what is advised is to run the container with a permanent volume in order not to lose the data.
