### ISSUE TITLE
configure pid.file for taskd

### ISSUE THREAD

**Issue by Strubbl** [ogarcia/docker-taskd#2]
Hello,
the documentation says something about the pid.file. Is this necessary to user in the container, too?

The command given in the documentaion:
`$ taskd config --force pid.file $PWD/taskd.pid`

Link to that docu:
https://taskwarrior.org/docs/taskserver/configure.html

Default value is `pid.file=/tmp/taskd.pid`. Is that okay for usage in docker?

**Comment by ogarcia** [comment]
No. The pid file is optional and is used only for some monitoring systems to locate the pid of taskd. If you don't have anyof these systems (or you have no idea what I'm talking about) you can ignore that setting.
