### ISSUE TITLE
Generated certificates use wrong CN

### ISSUE THREAD

**Issue by M-Gregoire** [ogarcia/docker-taskd#5]
Hello!
First of all, thank you for your work. It's working perfectly, however, I had to manually generate the CA certificates as the `CN` is set to `localhost` completely ignoring either `hostname` or the `CN` environment variable set in my `docker-compose.yml`.

```
Subject: C=SE,ST=Västra Götaland,L=Göteborg,O=Göteborg Bit Factory,CN=localhost
```

This lead to the following error on the client:
```
Handshake failed.  Error in the certificate.
```

I may have a missed something. Otherwise, I would be really great if the generated certificate could have a configurable CN, using either the hostname or an environment variable.

EDIT: I'm aware of the `vars` file in the `pki` folder. However, there is no easy way to trigger the certificate generate *from the container* after editing this `vars` file. The two only way I can think of currently are:
- Running the `generate` script from the host (Which means installing the certtools)
- Executing it with `docker exec`

In the second case, I believe a quick change of the `README.md` to add something like:
```
In the case you want to change the parameters used for the certificate generation,
- Delete everything in /pki/ except the generate scripts and the vars file
- Edit the vars file
- Run docker exec -it <container-id> /var/taskd/pki/generate
```

could be beneficial and isn't redundant with the taskwarrior doc.

I can make a PR if you want.

**Comment by ogarcia** [comment]
I see. Yes, send me a PR with the changes :wink:

**Comment by traycerb** [comment]
I tried this (deleting the `.pem` in the pki directory), editing the `vars` file and then running the command `docker exec -it <container-id> /var/taskd/pki/generate`  but i get the following error:

```
root@SynNAS-DS218:/srv/taskd/pki# docker exec -it taskd /var/taskd/pki/generate
/var/taskd/pki/generate: line 13: ./generate.ca: not found
/var/taskd/pki/generate: line 14: ./generate.server: not found
/var/taskd/pki/generate: line 20: ./generate.crl: not found
/var/taskd/pki/generate: line 27: ./generate.client: not found
```

The files are there, and it's strange that it can see and run the `generate` file, but not the scripts it references.

```
root@SynNAS-DS218:/srv/taskd/pki# ls -l
total 24
-rwxr-xr-x 1 root root 664 Feb 12 10:52 generate
-rwxr-xr-x 1 root root 633 Feb 12 10:52 generate.ca
-rwxr-xr-x 1 root root 778 Feb 12 10:52 generate.client
-rwxr-xr-x 1 root root 889 Feb 12 10:52 generate.crl
-rwxr-xr-x 1 root root 866 Feb 12 10:52 generate.server
-rw-r--r-- 1 root root 238 Feb 12 11:10 vars
```

I'm on a Synology NAS, but I tried it on Windows WSL too, and in both cases the initial run generates the appropriate certs and keys, but deleting and trying again results in the `not found` errors.  I'm sure this is something simple, but not sure how to move forward

**Comment by traycerb** [comment]
@ogarcia I didn't want to open a new issue, but I did get a little further.  doing a `docker exec -it CONTAINER /bin/sh` and manually switching to the directory and running `./generate` worked.

My issue now (out of scope TBH), is the certificates do not match names.  I'm trying to get it to run on my home-based Synology NAS and access taskd remotely, but I get this error on `task sync init`
```

Handshake failed. The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected.
Sync failed.  Could not connect to the Taskserver.
```

I've tried multiple hostnames in the `CN` field in the `vars` file (tried WAN IP +/- ports, LAN IP +/- ports, the `hostname -f` from within the Docker, which is just the Container ID), but can't seem to get anywhere.  Is it not possible to do what I'm attempting?

**Comment by ogarcia** [comment]
@traycerb You are right about the problems you have had in generating the certificates. The documentation was not quite correct. I have already modified it.

The most important thing for the certificate to work correctly is the CN, the rest of the fields can be modified if you want but, in this case, they will be rather aesthetic.

If to reach your machine from the client you go to the address `server.lan` that is what you have to put as CN. EXACTLY the same as you configure with `task config taskd.server` (in this case `task config taskd.server -- server.lan:53589`).
```shell
export CERT_CN=server.lan
./generate
```

Note that the port is NOT put in the CN and, obviously, the client certificates are generated after the server certificates have been generated.

As for not being able to reach the server remotely. Make sure that when you launch the container you have the `-p 53589:53589` option set to put the port listening. You will also have to check that your server does not have some kind of firewall that is cutting off access to that port from the outside.
