### ISSUE TITLE
Offer build instructions

### ISSUE THREAD

**Issue by jamesbiederbeck** [ogarcia/docker-taskd#7]
Just tried running on a pi4, and not unexpectedly, got:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Tried to build it myself:
```
$ git clone https://github.com/ogarcia/docker-taskd.git
$ docker build -t taskwarrior .
Sending build context to Docker daemon  144.4kB
Step 1/9 : ARG ALPINE_VERSION
Step 2/9 : FROM alpine:${ALPINE_VERSION}
invalid reference format
```
Oh, I have to define alpine version, as I see in your docker file. 

Maybe you can add a default to this? I just changed it to build on alpine:latest.

**Comment by ogarcia** [comment]
I don't offer build instructions because since it have a Makefile is very simple:
```
$ git clone https://github.com/ogarcia/docker-taskd.git
make
```

And voilá, you have a `connectical/taskd` docker image :smile:

**Comment by jamesbiederbeck** [comment]
Dope, went down the same rabbit hole again, forgot I had found this, ran into the same issues, went to open an Issue, and found this and your instructions.
