### ISSUE TITLE
I get a `X not found error` unless I am more specific in the script files

### ISSUE THREAD

**Issue by Dhamma-valence** [ogarcia/docker-taskd#8]
For whatever reason, the `generate` script fails unless I specify that the others (ca, client, crl, and server) are located at `/var/taskd/pki/`. So I just appended `/var/taskd/pki/` to each of the `./generate*` lines and it worked, and knew where they were.

Then I ran into the same issue with the var file and did the same, appending `. ./vars` with `/var/taskd/pki/` just before vars and it managed to find that as well. 

I'm not sure why I'm getting this issue as there aren't any other issues submitted referring to it, but luckily the workaround is super simple.

**Comment by ogarcia** [comment]
Are you running `generate` script from another directory other than `/var/taskd/pki/`? (or the directory that you have defined in `${TASKDDATA}`). If yes, this is the cause.

For example, if you are using the default `/var/taskd/pki/` you cannot execute `/var/taskd/pki/generate` from `/` or `/root` or whatever, you must do:
```sh
cd /var/taskd/pki/
./generate
```
