### ISSUE TITLE
Sync on ionotify

### ISSUE THREAD

**Issue by mnzaki** [ogarcia/docker-taskd#9]
Hello folks!
I am trying to integrate this into your run.sh
https://github.com/bergercookie/taskwarrior-syncall

using ionotifyd https://wiki.alpinelinux.org/wiki/Inotifyd

would you merge such a change?
any hints or advice? especially regarding openrc use in docker?

**Comment by ogarcia** [comment]
According to what I can see in the taskwarrior-syncall repository, this software is intended to synchronize taskwarrior with third parties, taskd has nothing to do with this.

In any case this repository what it packages is taskd in docker, it doesn't go further and doesn't pretend to put more add-ons, so adding any software is out of the context.

**Comment by mnzaki** [comment]
Alright, thanks for the quick response!
